name: timetoevent
description: "timetoevent"
publish_to: 'ByteWizard'
version: 0.1.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  intl: ^0.20.2
  uuid: ^4.5.1
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  vibration: ^3.1.3
  web_socket_channel: ^3.0.3
  provider: ^6.1.5
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
