name: timetoevent
description: "timetoevent"
publish_to: 'https://bytewizard.ru'
version: 1.16.0+46

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  uuid: ^4.5.1
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  vibration: ^3.1.3
  web_socket_channel: ^3.0.3
  provider: ^6.1.5
  timezone: ^0.10.1
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_localization: ^0.3.3
  android_alarm_manager_plus: ^4.0.7
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"