// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBduSJ84TlzN3Od7thQOHc0qcNfovfdFtU',
    appId: '1:374421089500:android:51a42d43209cc2bb165819',
    messagingSenderId: '374421089500',
    projectId: 'timetoevent-1',
    storageBucket: 'timetoevent-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkAn3VM4fsWtXkYbOvBq3J5XICjBb2s5M',
    appId: '1:374421089500:ios:a66523d8268c4c96165819',
    messagingSenderId: '374421089500',
    projectId: 'timetoevent-1',
    storageBucket: 'timetoevent-1.firebasestorage.app',
    iosBundleId: 'com.bytewizard.timetoevent.timetoevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkAn3VM4fsWtXkYbOvBq3J5XICjBb2s5M',
    appId: '1:374421089500:ios:a66523d8268c4c96165819',
    messagingSenderId: '374421089500',
    projectId: 'timetoevent-1',
    storageBucket: 'timetoevent-1.firebasestorage.app',
    iosBundleId: 'com.bytewizard.timetoevent.timetoevent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBae9WYN8wZJui5jyRrrtMTpQVfWsW2CWw',
    appId: '1:374421089500:web:beeb038bf3ce7206165819',
    messagingSenderId: '374421089500',
    projectId: 'timetoevent-1',
    authDomain: 'timetoevent-1.firebaseapp.com',
    storageBucket: 'timetoevent-1.firebasestorage.app',
    measurementId: 'G-S2RNVJ4QLH',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBae9WYN8wZJui5jyRrrtMTpQVfWsW2CWw',
    appId: '1:374421089500:web:beeb038bf3ce7206165819',
    messagingSenderId: '374421089500',
    projectId: 'timetoevent-1',
    authDomain: 'timetoevent-1.firebaseapp.com',
    storageBucket: 'timetoevent-1.firebasestorage.app',
    measurementId: 'G-S2RNVJ4QLH',
  );

}