name: Master CI/CD + Telegram

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build-and-deploy:
    if: |
      github.event_name == 'push' || 
      (github.event.pull_request.merged == true && github.event_name == 'pull_request')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полный history для получения коммитов

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Generate metadata
      id: metadata
      run: |
        # Извлекаем данные из pubspec.yaml
        PROJECT_NAME=$(grep '^name:' pubspec.yaml | awk -F': ' '{print $2}' | tr -d '\r' | tr -d '"')
        VERSION=$(grep '^version:' pubspec.yaml | awk -F': ' '{print $2}' | cut -d'+' -f1 | tr -d '\r')
        
        # Получаем хэш и сообщение последнего коммита
        COMMIT_HASH=$(git rev-parse --short HEAD)
        COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\r')
        
        # Формируем имя файла
        TIMESTAMP=$(date +"%Y%m%d-%H%M")
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          IDENTIFIER="pr${GITHUB_EVENT_NUMBER}"
        else
          IDENTIFIER="build${GITHUB_RUN_NUMBER}"
        fi
        
        APK_NAME="${PROJECT_NAME}_v${VERSION}_${IDENTIFIER}_${TIMESTAMP}_${COMMIT_HASH}.apk"
        
        # Безопасная запись переменных в output (включая многострочный текст)
        {
          echo "project_name=$PROJECT_NAME"
          echo "version=$VERSION"
          echo "apk_name=$APK_NAME"
          echo "commit_message<<EOF"
          echo "$COMMIT_MESSAGE"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Build APK
      run: |
        flutter build apk --release --no-tree-shake-icons
        mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/${{ steps.metadata.outputs.apk_name }}

    - name: Upload APK to Telegram
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        APK_PATH="build/app/outputs/apk/release/${{ steps.metadata.outputs.apk_name }}"

        # Экранирование спецсимволов
        PROJECT_NAME=$(echo '${{ steps.metadata.outputs.project_name }}' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g')
        VERSION=$(echo '${{ steps.metadata.outputs.version }}' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g')
        COMMIT_MSG=$(echo '${{ steps.metadata.outputs.commit_message }}' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g' -e ':a;N;$!ba;s/\n/%0A/g')
        APK_FILENAME=$(echo '${{ steps.metadata.outputs.apk_name }}' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g')

        # Сообщение в Telegram
        MESSAGE="🚀 *Новая сборка\\!*%0A%0A📦 Проект: ${PROJECT_NAME}%0A🔖 Версия: ${VERSION}%0A📝 Коммит: \`${COMMIT_MSG}\`%0A📁 Файл: \`${APK_FILENAME}\`"

        # Отправка APK
        curl -F document=@"$APK_PATH" "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID}"

        # Отправка сообщения
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" \
          -d text="${MESSAGE}" \
          -d parse_mode="MarkdownV2"
