name: Master CI/CD + Telegram

on:
  push:
    branches: [master,pro]
  pull_request:
    branches: [master,pro]
    types: [closed]

jobs:
  build-and-deploy:
    if: |
      github.event_name == 'push' || 
      (github.event.pull_request.merged == true && github.event_name == 'pull_request')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полный history для получения коммитов

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Restore Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/key.jks
        chmod 600 android/app/key.jks
        ls -la android/app/key.jks

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake libgtk-3-dev liblzma-dev libavahi-client-dev libdbus-1-dev libxtst-dev libxkbfile-dev

    - name: Check Keystore
      run: |
        ls -la android/app/key.jks
        keytool -list -keystore android/app/key.jks -storepass 090807Dan4ik@

    - name: Install dependencies
      run: flutter pub get

    - name: Generate metadata
      id: metadata
      run: |
        # Извлекаем данные из pubspec.yaml
        PROJECT_NAME=$(grep '^name:' pubspec.yaml | awk -F': ' '{print $2}' | tr -d '\r' | tr -d '"')
        VERSION=$(grep '^version:' pubspec.yaml | awk -F': ' '{print $2}' | cut -d'+' -f1 | tr -d '\r')
        
        # Получаем хэш и сообщение последнего коммита
        COMMIT_HASH=$(git rev-parse --short HEAD)
        COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\r')
        
        # Формируем имя файла
        TIMESTAMP=$(date +"%Y%m%d-%H%M")
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          IDENTIFIER="pr${GITHUB_EVENT_NUMBER}"
        else
          IDENTIFIER="build${GITHUB_RUN_NUMBER}"
        fi
        
        APK_NAME="${PROJECT_NAME}_v${VERSION}_${IDENTIFIER}_${TIMESTAMP}_${COMMIT_HASH}.apk"
        
        # Безопасная запись переменных в output (включая многострочный текст)
        {
          echo "project_name=$PROJECT_NAME"
          echo "version=$VERSION"
          echo "apk_name=$APK_NAME"
          echo "commit_message<<EOF"
          echo "$COMMIT_MESSAGE"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Build Linux
      run: |
        flutter config --enable-linux-desktop
        flutter clean
        flutter pub get
        flutter build linux --release
        cd build/linux/x64/release/bundle
        zip -r ../../../../linux_app.zip .
        cd ../../../../
        # Удаляем .apk из имени файла
        APK_NAME_NO_EXT=$(echo "${{ steps.metadata.outputs.apk_name }}" | sed 's/\.apk$//')
        # Создаем папку build, если она не существует
        mkdir -p build
        # Перемещаем файл с экранированием пробелов
        mv "linux_app.zip" "build/linux_app_${APK_NAME_NO_EXT}.zip"

    - name: Upload Linux to Telegram
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        LINUX_PATH="build/linux_app_${{ steps.metadata.outputs.apk_name }}.zip"

        # Экранирование спецсимволов
        PROJECT_NAME=$(echo '${{ steps.metadata.outputs.project_name }}' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g')
        VERSION=$(echo '${{ steps.metadata.outputs.version }}' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g')
        COMMIT_MSG=$(echo '${{ steps.metadata.outputs.commit_message }}' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g' -e ':a;N;$!ba;s/\n/%0A/g')
        LINUX_FILENAME=$(echo 'linux_app_${{ steps.metadata.outputs.apk_name }}.zip' | sed -e 's/[_.*()>#+-=|{}$!]/\\&/g')

        # Сообщение в Telegram
        MESSAGE="🚀 *Новая сборка Linux\\!*%0A%0A📦 Проект: ${PROJECT_NAME}%0A🔖 Версия: ${VERSION}%0A📝 Коммит: \`${COMMIT_MSG}\`%0A📁 Файл: \`${LINUX_FILENAME}\`"

        # Отправка архива
        curl -F document=@"$LINUX_PATH" "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID}"

        # Отправка сообщения
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" \
          -d text="${MESSAGE}" \
          -d parse_mode="MarkdownV2"

    - name: Notify on Success
      if: success()
      run: |
        echo "All builds completed successfully!"
        echo "APK Name: ${{ steps.metadata.outputs.apk_name }}"
        echo "Version: ${{ steps.metadata.outputs.version }}"
        echo "Project Name: ${{ steps.metadata.outputs.project_name }}"
        echo "Commit Message: ${{ steps.metadata.outputs.commit_message }}"
        # Sending success message to Telegram
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="✅ All builds completed successfully!%0A%0AAPK Name: `${{ steps.metadata.outputs.apk_name }}`%0AVersion: `${{ steps.metadata.outputs.version }}`%0AProject Name: `${{ steps.metadata.outputs.project_name }}`%0ACommit Message: `${{ steps.metadata.outputs.commit_message }}`" \
          -d parse_mode="MarkdownV2"
    
    - name: Notify on Failure
      if: failure()
      run: |
        echo "Build failed!"
        echo "Check the logs for details."
        echo "APK Name: ${{ steps.metadata.outputs.apk_name }}"
        echo "Version: ${{ steps.metadata.outputs.version }}"
        echo "Project Name: ${{ steps.metadata.outputs.project_name }}"
        echo "Commit Message: ${{ steps.metadata.outputs.commit_message }}"
        # Sending failure message to Telegram
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="❌ Build failed!%0A%0AAPK Name: `${{ steps.metadata.outputs.apk_name }}`%0AVersion: `${{ steps.metadata.outputs.version }}`%0AProject Name: `${{ steps.metadata.outputs.project_name }}`%0ACommit Message: `${{ steps.metadata.outputs.commit_message }}`" \
          -d parse_mode="MarkdownV2"

  build-windows:
    if: |
      github.event_name == 'push' || 
      (github.event.pull_request.merged == true && github.event_name == 'pull_request')
    runs-on: windows-latest
    needs: build-and-deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: |
        flutter clean
        flutter pub get
        flutter build windows --release
        cd build\windows\runner\Release
        7z a -tzip ..\..\..\windows_app.zip *
        cd ..\..\..
        move windows_app.zip build\windows_app_${{ needs.build-android-web-linux.outputs.apk_name }}.zip

    - name: Upload Windows to Telegram
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        $WINDOWS_PATH = "build\windows_app_${{ needs.build-android-web-linux.outputs.apk_name }}.zip"
        $PROJECT_NAME = '${{ needs.build-android-web-linux.outputs.project_name }}'.Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')
        $VERSION = '${{ needs.build-android-web-linux.outputs.version }}'.Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')
        $COMMIT_MSG = '${{ needs.build-android-web-linux.outputs.commit_message }}'.Replace('\n', '%0A').Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')
        $WINDOWS_FILENAME = 'windows_app_${{ needs.build-android-web-linux.outputs.apk_name }}.zip'.Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')

        $MESSAGE = "🚀 *Новая сборка Windows\!*%0A%0A📦 Проект: $PROJECT_NAME%0A🔖 Версия: $VERSION%0A📝 Коммит: `$COMMIT_MSG`%0A📁 Файл: `$WINDOWS_FILENAME`"

        curl -F "document=@$WINDOWS_PATH" "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendDocument?chat_id=${{ env.CHAT_ID }}"
        curl -s -X POST "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendMessage" `
          -d "chat_id=${{ env.CHAT_ID }}" `
          -d "text=$MESSAGE" `
          -d "parse_mode=MarkdownV2"