name: Master CI/CD + Telegram

on:
  push:
    branches: [master, pro]
  pull_request:
    branches: [master, pro]
    types: [closed]

jobs:
  build-and-deploy:
    if: |
      github.event_name == 'push' || 
      (github.event.pull_request.merged == true && github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.metadata.outputs.project_name }}
      version: ${{ steps.metadata.outputs.version }}
      apk_name: ${{ steps.metadata.outputs.apk_name }}
      apk_name_no_ext: ${{ steps.metadata.outputs.apk_name_no_ext }}
      commit_message: ${{ steps.metadata.outputs.commit_message }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build-windows:
    if: |
      github.event_name == 'push' || 
      (github.event.pull_request.merged == true && github.event_name == 'pull_request')
    runs-on: windows-latest
    needs: build-and-deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: |
        flutter clean
        flutter pub get
        flutter build windows --release
        cd build\windows\x64\runner\Release
        7z a -tzip ..\..\..\..\windows_app.zip *
        cd ..\..\..\..
        move windows_app.zip build\windows_app_${{ needs.build-and-deploy.outputs.apk_name_no_ext }}.zip

    - name: Upload Windows to Telegram
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        $WINDOWS_PATH = "build\windows_app_${{ needs.build-and-deploy.outputs.apk_name_no_ext }}.zip"
        $PROJECT_NAME = '${{ needs.build-and-deploy.outputs.project_name }}'.Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')
        $VERSION = '${{ needs.build-and-deploy.outputs.version }}'.Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')
        $COMMIT_MSG = '${{ needs.build-and-deploy.outputs.commit_message }}'.Replace('\n', '%0A').Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')
        $WINDOWS_FILENAME = 'windows_app_${{ needs.build-and-deploy.outputs.apk_name_no_ext }}.zip'.Replace(' ', '\ ').Replace('(', '\(').Replace(')', '\)').Replace('[', '\[').Replace(']', '\]').Replace('{', '\{').Replace('}', '\}').Replace('$', '\$').Replace('!', '\!')

        $MESSAGE = "🚀 *Новая сборка Windows\!*%0A%0A📦 Проект: $PROJECT_NAME%0A🔖 Версия: $VERSION%0A📝 Коммит: `$COMMIT_MSG`%0A📁 Файл: `$WINDOWS_FILENAME`"

        curl -F "document=@$WINDOWS_PATH" "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendDocument?chat_id=${{ env.CHAT_ID }}"
        curl -s -X POST "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendMessage" `
          -d "chat_id=${{ env.CHAT_ID }}" `
          -d "text=$MESSAGE" `
          -d "parse_mode=MarkdownV2"